import { useEffect, useState } from 'react'
import { Menu, X } from 'lucide-react'
import { motion } from 'framer-motion'
const links = [{ label: 'Home', target: 'home' }, { label: 'About', target: 'about' }, { label: 'Skills', target: 'skills' }, { label: 'Projects', target: 'projects' }, { label: 'Education', target: 'education' }, { label: 'Activity', target: 'github' }, { label: 'Contact', target: 'contact' }]
export default function Navbar() {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); const [active, setActive] = useState('Home')
  useEffect(() => { const onScroll = () => { setScrolled(scrollY > 30); const section = links.map((link) => document.getElementById(link.target)).find((element) => element && element.getBoundingClientRect().top < 180 && element.getBoundingClientRect().bottom > 180); if (section) setActive(links.find((link) => link.target === section.id)?.label || 'Home') }; addEventListener('scroll', onScroll, { passive: true }); return () => removeEventListener('scroll', onScroll) }, [])
  return <motion.header className={`navbar ${scrolled ? 'navbar--scrolled' : ''}`} initial={{ y: -30, opacity: 0 }} animate={{ y: 0, opacity: 1 }}><a className="brand" href="#home" aria-label="Pradeep Rakavi home" onClick={() => setOpen(false)}><span className="brand-mark">PR</span></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><nav className={open ? 'nav-links nav-links--open' : 'nav-links'} aria-label="Primary navigation">{links.map((link) => <a className={active === link.label ? 'active' : ''} href={`#${link.target}`} key={link.target} onClick={() => setOpen(false)}>{link.label}</a>)}</nav><a className="nav-status" href="https://github.com/Pradeep479182"><span className="status-dot" /> available for work</a></motion.header>
}
