import './App.css'
import { useEffect, useState } from 'react'
import { Code2, UserRound } from 'lucide-react'
import Navbar from './components/Navbar'
import CinematicHero from './components/CinematicHero'
import About from './components/About'
import TechnicalSkills from './components/TechnicalSkills'
import Projects from './components/Projects'
import Education from './components/Education'
import GitHubStats from './components/GitHubStats'
import Contact from './components/Contact'
import Footer from './components/Footer'
const GITHUB_USERNAME = 'Pradeep479182'
export default function App() { const [github, setGithub] = useState({ user: null, events: [], loading: true }); useEffect(() => { let active = true; const syncGithub = async () => { try { const responses = await Promise.all([fetch(`https://api.github.com/users/${GITHUB_USERNAME}`), fetch(`https://api.github.com/users/${GITHUB_USERNAME}/events/public?per_page=8`)]); if (!responses[0].ok) throw new Error('GitHub unavailable'); const [user, events] = await Promise.all([responses[0].json(), responses[1].ok ? responses[1].json() : []]); if (active) setGithub({ user, events, loading: false }) } catch { if (active) setGithub((current) => ({ ...current, loading: false })) } }; syncGithub(); const dailyRefresh = window.setInterval(syncGithub, 86400000); return () => { active = false; window.clearInterval(dailyRefresh) } }, []); return <div className="site-shell"><Navbar /><main><CinematicHero /><About /><TechnicalSkills /><Projects /><Education /><GitHubStats github={github} username={GITHUB_USERNAME} /><Contact /></main><Footer /><div className="social-rail"><a href="https://github.com/Pradeep479182" aria-label="GitHub"><Code2 size={16} /></a><a href="https://www.linkedin.com/in/pradeep-rakavi-27146b38b/" aria-label="LinkedIn"><UserRound size={16} /></a></div></div> }
